import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

// Import Isar collection schemas
// These files (e.g., user_profile.g.dart) are generated by build_runner
// For this script, we assume they will exist after generation.
import 'package:fmapp/src/features/auth/data/models/user_profile.dart';
import 'package:fmapp/src/features/sim_cards/data/models/sim_card.dart';
import 'package:fmapp/src/features/financial_accounts/data/models/financial_account.dart';

// Provider for the IsarService instance
final isarServiceProvider = Provider<IsarService>((ref) {
  // This typically shouldn't be instantiated directly like this in a provider
  // if init is async. The Isar instance itself should be what's provided.
  // Let's refine this: provide the Isar instance after it's initialized.
  throw UnimplementedError("Isar instance should be provided via isarInstanceProvider after initialization in main.dart");
});

// Provider for the Isar instance itself
// This will be overridden in main.dart after Isar is initialized.
final isarInstanceProvider = Provider<Isar>((ref) {
  // This will throw if accessed before Isar is initialized and the provider overridden.
  // Consider using a FutureProvider if you need to handle the async nature directly in widgets,
  // but for a global instance initialized at startup, overriding is common.
  throw Exception("Isar instance not initialized. Ensure IsarService.init() is called at startup and isarInstanceProvider is overridden.");
});


class IsarService {
  late final Isar _isar;

  Isar get instance => _isar;

  IsarService() {
    // Constructor can be empty if init is called explicitly.
    // Or, make init private and call from a static factory method that returns Future<IsarService>.
  }

  Future<void> init() async {
    final dir = await getApplicationDocumentsDirectory();
    try {
      _isar = await Isar.open(
        [
          UserProfileSchema, // Generated by build_runner
          SimCardSchema,     // Generated by build_runner
          FinancialAccountSchema, // Generated by build_runner
          // Add other schemas here as they are created
        ],
        directory: dir.path,
        name: 'fmappLocalDB', // Optional custom name for the Isar instance
      );
      print("Isar initialized successfully at ${dir.path}/fmappLocalDB.isar");
    } catch (e) {
      // Handle initialization error
      print("Error initializing Isar: $e");
      // Potentially rethrow or handle critical failure
      rethrow;
    }
  }

  // Convenience method to get the Isar instance, though provider is preferred.
  Isar get db => _isar;

  // Optional: Add methods for common operations like clear database for testing, etc.
  Future<void> clearDatabase() async {
    await _isar.writeTxn(() async {
      await _isar.clear();
    });
    print("Isar database cleared.");
  }
}
