import 'package:fmapp/src/features/auth/presentation/state/auth_controller.dart';
import 'package:fmapp/src/features/sim_cards/data/models/sim_card.dart';
import 'package:fmapp/src/features/sim_cards/presentation/state/sim_card_controller.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:fmapp/src/core/presentation/widgets/custom_text_form_field.dart';
import 'package:isar/isar.dart'; // For Id type

class AddEditSimCardScreen extends ConsumerStatefulWidget {
  final SimCard? simCard; // Null if adding, populated if editing

  const AddEditSimCardScreen({super.key, this.simCard});

  @override
  ConsumerState<AddEditSimCardScreen> createState() => _AddEditSimCardScreenState();
}

class _AddEditSimCardScreenState extends ConsumerState<AddEditSimCardScreen> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _phoneNumberController;
  late TextEditingController _nicknameController;
  late TextEditingController _telecomProviderController;
  late TextEditingController _officialNameController;
  late TextEditingController _colorCodeController; // Example: #RRGGBB

  bool get _isEditing => widget.simCard != null;

  @override
  void initState() {
    super.initState();
    _phoneNumberController = TextEditingController(text: widget.simCard?.phoneNumber ?? '');
    _nicknameController = TextEditingController(text: widget.simCard?.simNickname ?? '');
    _telecomProviderController = TextEditingController(text: widget.simCard?.telecomProvider ?? '');
    _officialNameController = TextEditingController(text: widget.simCard?.officialRegisteredName ?? '');
    _colorCodeController = TextEditingController(text: widget.simCard?.colorCode ?? '');
  }

  @override
  void dispose() {
    _phoneNumberController.dispose();
    _nicknameController.dispose();
    _telecomProviderController.dispose();
    _officialNameController.dispose();
    _colorCodeController.dispose();
    super.dispose();
  }

  Future<void> _saveSimCard() async {
    if (_formKey.currentState!.validate()) {
      final currentUserId = ref.read(authControllerProvider).value?.id;
      if (currentUserId == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Error: User not authenticated.')),
        );
        return;
      }

      final now = DateTime.now();
      final simCardData = SimCard(
        isarId: widget.simCard?.isarId ?? Isar.autoIncrement,
        supabaseId: widget.simCard?.supabaseId, // Will be generated by repo if null on add
        userId: currentUserId,
        phoneNumber: _phoneNumberController.text.trim(),
        simNickname: _nicknameController.text.trim(),
        telecomProvider: _telecomProviderController.text.trim().isNotEmpty ? _telecomProviderController.text.trim() : null,
        officialRegisteredName: _officialNameController.text.trim().isNotEmpty ? _officialNameController.text.trim() : null,
        colorCode: _colorCodeController.text.trim().isNotEmpty ? _colorCodeController.text.trim() : null,
        createdAt: widget.simCard?.createdAt ?? now,
        updatedAt: now,
      );

      try {
        final notifier = ref.read(simCardControllerProvider.notifier);
        if (_isEditing) {
          await notifier.updateSimCard(simCardData);
        } else {
          await notifier.addSimCard(simCardData);
        }
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('SIM Card ${_isEditing ? "updated" : "added"} successfully!')),
          );
          Navigator.of(context).pop(); // Go back after save
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Error saving SIM Card: ${e.toString()}')),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final isLoading = ref.watch(simCardControllerProvider).isLoading;

    return Scaffold(
      appBar: AppBar(
        title: Text(_isEditing ? 'Edit SIM Card' : 'Add New SIM Card'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              CustomTextFormField(
                controller: _phoneNumberController,
                labelText: 'Phone Number*',
                hintText: 'e.g., 0911xxxxxx',
                keyboardType: TextInputType.phone,
                prefixIcon: Icons.phone_android,
                validator: (value) {
                  if (value == null || value.isEmpty) return 'Phone number is required';
                  // Basic validation, can be improved
                  if (!RegExp(r'^[0-9\+]+$').hasMatch(value)) return 'Enter a valid phone number';
                  return null;
                },
              ),
              CustomTextFormField(
                controller: _nicknameController,
                labelText: 'SIM Nickname*',
                hintText: 'e.g., My Main SIM, Work SIM',
                prefixIcon: Icons.label_outline,
                validator: (value) {
                  if (value == null || value.isEmpty) return 'Nickname is required';
                  return null;
                },
              ),
              CustomTextFormField(
                controller: _telecomProviderController,
                labelText: 'Telecom Provider',
                hintText: 'e.g., Ethio telecom, Safaricom',
                 prefixIcon: Icons.network_cell,
              ),
              CustomTextFormField(
                controller: _officialNameController,
                labelText: 'Official Registered Name',
                hintText: 'Optional',
                prefixIcon: Icons.person_outline,
              ),
              CustomTextFormField(
                controller: _colorCodeController,
                labelText: 'Color Code',
                hintText: 'e.g., #FF0000 or blue (for UI)',
                prefixIcon: Icons.color_lens_outlined,
              ),
              const SizedBox(height: 24),
              isLoading
                  ? const Center(child: CircularProgressIndicator())
                  : ElevatedButton.icon(
                      icon: Icon(_isEditing ? Icons.save_alt : Icons.add_circle_outline),
                      onPressed: _saveSimCard,
                      label: Text(_isEditing ? 'Save Changes' : 'Add SIM Card'),
                    ),
            ],
          ),
        ),
      ),
    );
  }
}
